import React, {useState, useEffect} from 'react';
import {useApp,api,navigate,Link,Modal,Icon,Button,Field,ErrorBox,Notice,Empty,Badge,Avatar,formatDate,download,latestEvidence} from './core';

function useFormAction(close){const {refresh,toast}=useApp();const [busy,setBusy]=useState(false),[error,setError]=useState('');return {busy,error,setError,async run(fn,message,after){if(busy)return;setBusy(true);setError('');try{const result=await fn();await refresh();if(message)toast(message);close();after?.(result);}catch(e){setError(e.message);}finally{setBusy(false);}}};}
function Actions({busy,onClose,label='Save changes',icon}){return <div className="form-actions"><Button type="button" variant="secondary" disabled={busy} onClick={onClose}>Cancel</Button><Button type="submit" icon={icon} busy={busy}>{label}</Button></div>;}

function StudentForm({student,onClose}){
 const {workspace}=useApp(); const [f,setF]=useState(student?{...student}:{name:'',roll:'',reg_no:'',semester:5,section:'A',email:'',phone:'',current_cgpa:'',target_cgpa:8.5,portal_password:'Nexora@1234'}),a=useFormAction(onClose);
 const set=(k,v)=>setF(x=>({...x,[k]:v}));
 return <form onSubmit={e=>{e.preventDefault();a.run(()=>api(student?`/students/${student.id}`:'/students',f,student?'PATCH':'POST'),student?'Student updated.':'Student added.',r=>{if(!student)navigate(`/app/students/${r.id}`);});}}>
 <ErrorBox>{a.error}</ErrorBox><div className="form-grid"><Field label="Student name"><input autoFocus required minLength={2} maxLength={80} value={f.name} onChange={e=>set('name',e.target.value)} placeholder="Student full name"/></Field>
 <Field label="Roll number"><input required maxLength={32} value={f.roll} onChange={e=>set('roll',e.target.value.toUpperCase())} placeholder="23CSE101"/></Field>
 <Field label="Registration number"><input maxLength={40} value={f.reg_no||''} onChange={e=>set('reg_no',e.target.value)} placeholder="Optional"/></Field>
 <Field label="Semester"><select value={f.semester} onChange={e=>set('semester',Number(e.target.value))}>{[1,2,3,4,5,6,7,8].map(n=><option key={n} value={n}>{n}</option>)}</select></Field>
 <Field label="Section"><input required maxLength={8} value={f.section} onChange={e=>set('section',e.target.value.toUpperCase())}/></Field>
 <Field label="Email"><input type="email" value={f.email||''} onChange={e=>set('email',e.target.value)} placeholder="student@college.edu"/></Field>
 <Field label="Phone"><input inputMode="tel" maxLength={20} value={f.phone||''} onChange={e=>set('phone',e.target.value)} placeholder="Optional"/></Field>
 <Field label="Current CGPA"><input type="number" min="0" max="10" step="0.01" value={f.current_cgpa??''} onChange={e=>set('current_cgpa',e.target.value)} placeholder="Optional"/></Field>
 <Field label="Target CGPA"><input type="number" min="0" max="10" step="0.01" value={f.target_cgpa??8.5} onChange={e=>set('target_cgpa',e.target.value)}/></Field>
 {!student&&<Field label="Initial portal password" hint="Give this to the student, or reset it later."><input minLength={10} maxLength={128} value={f.portal_password||''} onChange={e=>set('portal_password',e.target.value)}/></Field>}
 </div><Actions busy={a.busy} onClose={onClose} label={student?'Save student':'Add student'} icon="check"/></form>;
}

function EvidenceForm({student,plan,onClose}){
 const {workspace}=useApp();const latest=plan?(plan.progress.at(-1)||plan.data.baseline):null;const [f,setF]=useState({course:plan?.course||'DSA',assessment_type:latest?.assessment_type||'Assessment',score:latest?.score??'',attendance:latest?.attendance??'',completion:latest?.completion??'',recorded_on:workspace.server_date,topic:'',notes:''}),a=useFormAction(onClose);const set=(k,v)=>setF({...f,[k]:v});
 return <form onSubmit={e=>{e.preventDefault();a.run(()=>api(plan?`/plans/${plan.id}/progress`:`/students/${student.id}/evidence`,f),plan?'Progress recorded. Recommendations updated.':'Academic Data recorded. Support signals updated.');}}><ErrorBox>{a.error}</ErrorBox><div className="form-context"><Icon name={plan?'chart':'file'} size={22}/><div><strong>{plan?workspace.students.find(s=>s.id===plan.student_id)?.name:student.name}</strong><span>{plan?`${plan.course} · Log a comparable follow-up assessment`:`${student.roll} · Course performance evidence`}</span></div></div><div className="form-grid"><Field label="Course"><select value={f.course} disabled={!!plan} onChange={e=>set('course',e.target.value)}>{Object.entries(workspace.courses).map(([k,v])=><option key={k} value={k}>{k} — {v.name}</option>)}</select></Field><Field label="Recorded on"><input type="date" required value={f.recorded_on} max={workspace.server_date} min={plan?(plan.progress.at(-1)?.recorded_on||plan.data.baseline.recorded_on):'2000-01-01'} onChange={e=>set('recorded_on',e.target.value)}/></Field></div><div className="form-grid three">{[['score','Assessment (%)'],['attendance','Attendance (%)'],['completion','Assignments (%)']].map(([k,l])=><Field label={l} key={k}><input required type="number" step="0.1" min="0" max="100" placeholder="0–100" value={f[k]} onChange={e=>set(k,e.target.value)}/></Field>)}</div>{!plan&&<Field label="Learning-gap topic (optional)" hint="Academic topic only. This may be sent to your selected AI provider; do not include personal information."><input maxLength={160} placeholder="e.g. Recursion and call-stack tracing" value={f.topic} onChange={e=>set('topic',e.target.value)}/></Field>}<Field label={plan?'Faculty reflection (optional)':'Faculty note (optional)'} hint="Notes remain local and are not sent to the AI provider."><textarea rows={3} maxLength={1000} value={f.notes} onChange={e=>set('notes',e.target.value)} placeholder={plan?'What helped? What should change at the next review?':'Add academic context, not personal assumptions.'}/></Field><Actions busy={a.busy} onClose={onClose} label={plan?'Save check-in':'Save evidence'} icon="check"/></form>;
}

function GenerateForm({studentId,course,parentId,onClose}){
 const {workspace}=useApp();const [sid,setSid]=useState(studentId||''),[subject,setSubject]=useState(course||''),[weeks,setWeeks]=useState(4),[settings,setSettings]=useState(null),[settingsError,setSettingsError]=useState('');const a=useFormAction(onClose);
 useEffect(()=>{api('/settings').then(setSettings).catch(e=>setSettingsError(e.message));},[]);
 const student=workspace.students.find(s=>s.id===Number(sid));const courses=student?latestEvidence(student.evidence):[];
 useEffect(()=>{if(courses.length&&!courses.some(c=>c.course===subject))setSubject(courses[0].course);if(!courses.length)setSubject('');},[sid]);
 if(!workspace.students.length)return <Empty title="Add a student first" description="Planning needs a student and at least one course evidence record."><Button onClick={()=>{onClose();navigate('/app/students');}}>Go to students</Button></Empty>;
 return <form onSubmit={e=>{e.preventDefault();a.run(()=>api('/plans/generate',{student_id:Number(sid),course:subject,weeks,parent_id:parentId||null}),parentId?'Revision drafted. Faculty review required.':'Study Plan drafted. Review it before approval.',r=>navigate(`/app/plans/${r.id}`));}}><ErrorBox>{a.error||settingsError}</ErrorBox><Notice icon="layers">{parentId?'A fresh draft will use subsequent evidence and the progress evaluation. Your current plan remains active until approval.':'The workflow validates evidence, evaluates support signals, selects a resource and drafts a plan for your review.'}</Notice><Field label="Student"><select required value={sid} disabled={!!parentId} onChange={e=>setSid(e.target.value)}><option value="">Select a student</option>{workspace.students.map(s=><option value={s.id} key={s.id}>{s.name} · {s.roll}</option>)}</select></Field><div className="form-grid"><Field label="Course with evidence"><select required value={subject} disabled={!courses.length||!!parentId} onChange={e=>setSubject(e.target.value)}><option value="">Choose a course</option>{courses.map(c=><option value={c.course} key={c.course}>{c.course} · assessment {c.score}%</option>)}</select></Field><Field label="Plan duration"><select value={weeks} onChange={e=>setWeeks(Number(e.target.value))}>{[1,2,3,4,6,8].map(n=><option key={n} value={n}>{n} week{n>1?'s':''}</option>)}</select></Field></div>{student&&!courses.length&&<Notice tone="orange" icon="info">No course evidence is available. Open the student’s page and add evidence before generating a plan.</Notice>}<div className="generation-provider"><div className="feature-icon"><Icon name="bolt" size={21}/></div><div><strong>{settings?settings.provider==='rules'?'Local rules planner':settings.provider==='gemini'?'Gemini generation':'Local Ollama generation':'Loading AI configuration...'}</strong><span>{settings?.provider==='rules'?'Deterministic evidence-based templates. No language model or network request.':settings?.provider==='gemini'?'Minimized academic evidence is sent to Google. Your free-tier quota applies.':'Requires the chosen model installed and Ollama running on the server.'}</span></div><button type="button" className="text-link" onClick={()=>{onClose();navigate('/app/settings');}}>Settings<Icon name="arrow" size={16}/></button></div>{a.busy&&<div className="generation-running" role="status"><span className="spinner"/><div><strong>Preparing a thoughtful study plan…</strong><span>{settings?.provider==='ollama'?'A local model can take up to two minutes.':'Waiting for the planning workflow to finish.'} You can close this dialog and check Study Plans later.</span></div></div>}<Actions busy={a.busy} onClose={onClose} label={parentId?'Generate revision draft':'Generate study plan'} icon="layers"/><p className="form-footnote">Drafts are never automatically activated. Provider errors do not trigger a paid fallback.</p></form>;
}

const template='name,roll,semester,section,course,score,attendance,completion,topic,notes,recorded_on\nDemo Student,DEMO001,5,A,DSA,42,68,55,Recursion,Synthetic sample,\nDemo Student,DEMO001,5,A,DBMS,58,76,70,SQL joins,Synthetic sample,\n';
function parseCsv(raw){
 const rows=[];let row=[],cell='',quoted=false;
 for(let i=0;i<raw.length;i++){const ch=raw[i];if(quoted){if(ch==='"'){if(raw[i+1]==='"'){cell+='"';i++;}else quoted=false;}else cell+=ch;}else if(ch==='"'){quoted=true;}else if(ch===','){row.push(cell);cell='';}else if(ch==='\n'){row.push(cell);rows.push(row);row=[];cell='';}else if(ch!=='\r'){cell+=ch;}}
 if(cell.length||row.length){row.push(cell);rows.push(row);}return rows.filter(r=>r.some(v=>String(v).trim()!==''));
}
const IMPORT_FIELDS=[['name','Student name'],['roll','Roll number'],['semester','Semester'],['section','Section'],['course','Course'],['score','Score / marks'],['attendance','Attendance %'],['completion','Assignment completion %'],['email','Email'],['reg_no','Registration number'],['phone','Phone'],['assessment_type','Assessment type'],['topic','Topic'],['notes','Notes'],['recorded_on','Recorded date']];
function normHeader(x){return String(x||'').trim().toLowerCase().replace(/[^a-z0-9]+/g,'_').replace(/^_|_$/g,'');}
function ImportForm({onClose}){
 const [raw,setRaw]=useState(''),[name,setName]=useState(''),[step,setStep]=useState(1),[mapping,setMapping]=useState({}),[rows,setRows]=useState([]),[validation,setValidation]=useState(null),[busy,setBusy]=useState(false);const {refresh,toast}=useApp();const [error,setError]=useState('');
 const headers=()=>parseCsv(raw)[0]||[];
 function build(file){setName(file.name);file.text().then(text=>{const parsed=parseCsv(text),hs=parsed[0]||[],initial={};hs.forEach((h,i)=>{const n=normHeader(h);const aliases={'student_roll':'roll','student_name':'name','roll_number':'roll','marks':'score','attendance_percentage':'attendance','assignment':'completion','assessment':'assessment_type','date':'recorded_on','registration_number':'reg_no'};const hit=IMPORT_FIELDS.find(([k])=>k===n||k===aliases[n]);if(hit)initial[i]=hit[0];});setRaw(text);setMapping(initial);setRows([]);setValidation(null);setError('');setStep(2);}).catch(()=>setError('The CSV file could not be read.'))}
 function applyMapping(){const hs=headers();setRows(parseCsv(raw).slice(1).map(r=>Object.fromEntries(hs.map((h,i)=>[mapping[i]||normHeader(h),r[i]??'']))));setStep(3)}
 function validate(){const required=['name','roll','semester','section','course','score','attendance','completion'];const mapped=new Set(Object.values(mapping));const problems=[];if(!required.every(k=>mapped.has(k)))problems.push(`Missing required columns: ${required.filter(k=>!mapped.has(k)).join(', ')}.`);const seen=new Set();const rowErrors=[];rows.forEach((r,i)=>{const line=i+2,score=Number(r.score),att=Number(r.attendance),comp=Number(r.completion),key=`${String(r.roll).trim().toUpperCase()}|${String(r.course).trim()}|${r.recorded_on||'today'}`;if(!r.name||!r.roll||!r.course)rowErrors.push(`Row ${line}: name, roll and course are required.`);if(!Number.isFinite(score)||score<0||score>100)rowErrors.push(`Row ${line}: score must be between 0 and 100.`);if(!Number.isFinite(att)||att<0||att>100)rowErrors.push(`Row ${line}: attendance must be between 0 and 100.`);if(!Number.isFinite(comp)||comp<0||comp>100)rowErrors.push(`Row ${line}: completion must be between 0 and 100.`);if(seen.has(key))rowErrors.push(`Row ${line}: duplicate roll/course/date in this file.`);seen.add(key);});setValidation({valid:Math.max(0,rows.length-rowErrors.length),invalid:rowErrors.length+problems.length,total:rows.length,errors:[...problems,...rowErrors].slice(0,24)});setStep(4)}
 function csv(){const hs=['name','roll','semester','section','course','score','attendance','completion','email','topic','notes','recorded_on','reg_no','phone','assessment_type'];const q=v=>`"${String(v??'').replace(/"/g,'""')}"`;return [hs.join(','),...rows.map(r=>hs.map(h=>q(r[h])).join(','))].join('\n')}
 async function process(){if(busy)return;setBusy(true);setError('');try{await api('/students/import',{csv:csv()});await refresh();toast('Academic data imported successfully.');setStep(7);setTimeout(onClose,700);}catch(e){setError(e.message)}finally{setBusy(false)}}
 const labels=['Upload','Detect','Map','Validate','Preview','Confirm','Done'];return <div>
  <div className="import-steps">{labels.map((x,i)=><div key={x} className={step===i+1?'active':step>i+1?'done':''}><span>{i+1}</span>{x}</div>)}</div><ErrorBox>{error}</ErrorBox>
  {step===1&&<><p className="form-description">Bring marks, attendance and course evidence into the workspace. Nothing is written until you confirm the final import.</p><label className="upload-zone"><Icon name="upload" size={30}/><strong>Choose an academic CSV</strong><span>CSV only · up to 500 KB</span><input type="file" accept=".csv,text/csv" onChange={e=>{const f=e.target.files?.[0];if(f){if(f.size>500000){setError('Choose a CSV file smaller than 500 KB.');return}build(f)}}}/></label><div className="template-row"><span>Use the template to avoid column mapping.</span><Button type="button" variant="secondary" icon="download" onClick={()=>download(template,'nexora-evidence-template.csv','text/csv')}>Download template</Button></div></>}
  {step===2&&<><p className="form-description"><strong>{name}</strong> contains {headers().length} columns. We matched common names automatically; confirm anything that needs changing.</p><div className="import-map-table"><div className="import-map-head"><span>CSV column</span><span>Nexora field</span></div>{headers().map((h,i)=><div className="import-map-row" key={i}><strong>{h}</strong><select value={mapping[i]||''} onChange={e=>setMapping(m=>({...m,[i]:e.target.value}))}><option value="">Do not import</option>{IMPORT_FIELDS.map(([k,l])=><option key={k} value={k}>{l}</option>)}</select></div>)}</div><div className="form-actions"><Button type="button" variant="secondary" onClick={()=>setStep(1)}>Back</Button><Button type="button" onClick={applyMapping}>Review mapping</Button></div></>}
  {step===3&&<><h3>Review mapping</h3><Notice icon="info">The same field can only be supplied once. Required fields are checked in the next step.</Notice><div className="mapping-summary">{Object.entries(mapping).filter(([,v])=>v).map(([i,v])=><span key={i}><strong>{headers()[i]}</strong><small>→ {IMPORT_FIELDS.find(x=>x[0]===v)?.[1]||v}</small></span>)}</div><div className="form-actions"><Button type="button" variant="secondary" onClick={()=>setStep(2)}>Back</Button><Button type="button" onClick={validate}>Validate data</Button></div></>}
  {step===4&&<><h3>Validation results</h3><div className="import-validation-grid"><div><strong>{validation?.valid||0}</strong><span>Valid rows</span></div><div><strong>{validation?.invalid||0}</strong><span>Rows needing fixes</span></div><div><strong>{validation?.total||0}</strong><span>Total rows</span></div></div>{validation?.errors?.length?<div className="import-errors">{validation.errors.map((x,i)=><div key={i}>{x}</div>)}</div>:<Notice tone="green" icon="check">All detected rows pass the basic checks. The server will run its final validation too.</Notice>}<div className="form-actions"><Button type="button" variant="secondary" onClick={()=>setStep(2)}>Back</Button><Button type="button" disabled={!!validation?.invalid} onClick={()=>setStep(5)}>Preview changes</Button></div></>}
  {step===5&&<><h3>Preview changes</h3><p className="form-description">Review the first 8 records before import.</p><div className="import-preview-table"><table><thead><tr>{['name','roll','course','score','attendance','completion'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.slice(0,8).map((r,i)=><tr key={i}>{['name','roll','course','score','attendance','completion'].map(h=><td key={h}>{r[h]||'—'}</td>)}</tr>)}</tbody></table></div><div className="form-actions"><Button type="button" variant="secondary" onClick={()=>setStep(4)}>Back</Button><Button type="button" onClick={()=>setStep(6)}>Confirm import</Button></div></>}
  {step===6&&<><h3>Ready to import</h3><Notice icon="shield">No records have been changed yet. The import is still reversible because it has not been processed.</Notice><p className="form-description">{rows.length} row{rows.length!==1?'s':''} will be sent to the server.</p><div className="form-actions"><Button type="button" variant="secondary" onClick={()=>setStep(5)}>Back</Button><Button type="button" busy={busy} onClick={process}>Process import</Button></div></>}
  {step===7&&<Notice tone="green" icon="check">Import completed successfully.</Notice>}
  {step<7&&<div className="form-actions"><Button type="button" variant="secondary" disabled={busy} onClick={onClose}>Cancel</Button></div>}
 </div>;
}

function ResetPassword({student,onClose}){
 const a=useFormAction(onClose); const [pw,setPw]=useState('Nexora@1234');
 return <form onSubmit={e=>{e.preventDefault();a.run(()=>api(`/students/${student.id}/reset-password`,{new_password:pw}),'Student password reset. Give the new temporary password to the student.');}}>
 <ErrorBox>{a.error}</ErrorBox><div className="form-context"><Icon name="lock" size={22}/><div><strong>Reset {student.name}'s portal password</strong><span>The current password is never shown or retrieved.</span></div></div><Field label="New temporary password" hint="At least 10 characters with a letter and a number."><input autoFocus required minLength={10} maxLength={128} value={pw} onChange={e=>setPw(e.target.value)}/></Field><Notice icon="shield">This signs the student into the same portal account after they use the new password; the student record is not deleted.</Notice><Actions busy={a.busy} onClose={onClose} label="Reset password" icon="lock"/></form>
}
function StudentTarget({student,onClose}){
 const a=useFormAction(onClose); const [target,setTarget]=useState(student.target_cgpa??8.5);
 return <form onSubmit={e=>{e.preventDefault();a.run(()=>api('/student/target',{target_cgpa:Number(target)},'PATCH'),'Target CGPA updated.');}}><ErrorBox>{a.error}</ErrorBox><Field label="Target CGPA"><input autoFocus type="number" min="0" max="10" step="0.01" value={target} onChange={e=>setTarget(e.target.value)}/></Field><p className="form-desc">Nexora will use this as a planning target. It will not invent university grading rules or promise a future CGPA.</p><Actions busy={a.busy} onClose={onClose} label="Save target" icon="target"/></form>
}

function EditPlanForm({plan:p,onClose}){const [f,setF]=useState(JSON.parse(JSON.stringify(p.data))),a=useFormAction(onClose);const set=(k,v)=>setF({...f,[k]:v});const task=(i,k,v)=>setF({...f,activities:f.activities.map((a,j)=>j===i?{...a,[k]:v}:a)});return <form onSubmit={e=>{e.preventDefault();a.run(()=>api(`/plans/${p.id}`,{action:'edit',...f},'PATCH'),'Draft updated.');}}><ErrorBox>{a.error}</ErrorBox><Field label="Study Plan title"><input required maxLength={160} value={f.title} onChange={e=>set('title',e.target.value)}/></Field><Field label="Personalized objective"><textarea required rows={3} maxLength={700} value={f.objective} onChange={e=>set('objective',e.target.value)}/></Field><div className="form-grid"><Field label="Target assessment (%)"><input type="number" min="0" max="100" step="0.1" required value={f.target_score} onChange={e=>set('target_score',e.target.value)}/></Field><Field label="Review date"><input type="date" required value={f.review_on} onChange={e=>set('review_on',e.target.value)}/></Field></div><h3 className="form-section-title">Activities & schedule</h3>{f.activities.map((t,i)=><div className="edit-task-form" key={i}><span className="eyebrow">ACTIVITY {i+1} / {t.kind.toUpperCase()}</span><Field label="Title"><input required minLength={3} maxLength={160} value={t.title} onChange={e=>task(i,'title',e.target.value)}/></Field><Field label="Instructions"><textarea required minLength={8} maxLength={900} rows={3} value={t.description} onChange={e=>task(i,'description',e.target.value)}/></Field><Field label="Due date"><input type="date" required value={t.due_on} onChange={e=>task(i,'due_on',e.target.value)}/></Field></div>)}<Actions busy={a.busy} onClose={onClose} label="Save draft" icon="check"/></form>;}

function ConfirmPlan({plan,type,onClose}){const a=useFormAction(onClose);const copy={approve:['Ready to put this plan into practice?','You confirm that you have reviewed the evidence, targets and activities. Approval archives any existing active plan for this student and course.','Approve & activate'],complete:['Close the loop.','All activities have been marked complete. This closes the plan without declaring that the learning goals have been achieved.','Complete plan'],archive:['Keep the context. Pause the action.','This plan and its progress history will remain available under Archived. It can no longer receive task or progress updates.','Archive plan']}[type];return <form onSubmit={e=>{e.preventDefault();a.run(()=>api(`/plans/${plan.id}`,{action:type},'PATCH'),`Plan ${type==='approve'?'approved':type==='archive'?'archived':'completed'}.`);}}><ErrorBox>{a.error}</ErrorBox><h3>{copy[0]}</h3><p className="form-description">{copy[1]}</p><div className="confirm-plan-title"><Icon name="layers"/>{plan.data.title}</div><Actions busy={a.busy} onClose={onClose} label={copy[2]} icon="check"/></form>;}

function TaskNote({plan,index,onClose}){const task=plan.data.activities[index];const [note,setNote]=useState(task.faculty_note||''),[complete,setComplete]=useState(task.completed),a=useFormAction(onClose);return <form onSubmit={e=>{e.preventDefault();a.run(()=>api(`/plans/${plan.id}`,{action:'task',index,completed:complete,faculty_note:note},'PATCH'),'Implementation note saved.');}}><ErrorBox>{a.error}</ErrorBox><div className="confirm-plan-title"><Icon name="file"/>{task.title}</div><Field label="Faculty implementation note"><textarea rows={4} maxLength={600} value={note} onChange={e=>setNote(e.target.value)} placeholder="Record what was completed and any observations."/></Field><label className="checkbox-field"><input type="checkbox" checked={complete} onChange={e=>setComplete(e.target.checked)}/><span>Mark this activity as complete</span></label><Actions busy={a.busy} onClose={onClose}/></form>;}

function DeleteStudent({student,onClose}){const [confirm,setConfirm]=useState(''),a=useFormAction(onClose);return <form onSubmit={e=>{e.preventDefault();a.run(()=>api(`/students/${student.id}`,{confirm},'DELETE'),'Student and associated records deleted.',()=>navigate('/app/students'));}}><ErrorBox>{a.error}</ErrorBox><Notice tone="orange" icon="trash"><strong>This cannot be undone.</strong> Deleting {student.name} also removes their evidence, plans and progress records from this workspace. Your prior exports are not affected.</Notice><Field label="Type DELETE to confirm"><input required value={confirm} onChange={e=>setConfirm(e.target.value)} autoComplete="off" placeholder="DELETE"/></Field><div className="form-actions"><Button type="button" variant="secondary" onClick={onClose}>Keep student</Button><Button variant="danger" disabled={confirm!=='DELETE'} busy={a.busy}>Delete permanently</Button></div></form>;}

function ExportPlan({plan:p,student:s,onClose}){const {toast}=useApp();function md(){const d=p.data;const content=`# ${d.title}\n\nNexora · Academic Study Plan Studio\n\nStudent: ${s.name} (${s.roll})\nCourse: ${p.course} | Status: ${p.status} | Revision: ${p.revision}\nSource: ${d.source} (${d.model})\n\n## Objective\n${d.objective}\n\n## Academic Data\n${d.rationale}\nBaseline assessment: ${d.baseline.score}%\nTarget assessment: ${d.target_score}%\nReview date: ${d.review_on}\n\n## Activities\n${d.activities.map(a=>`- [${a.completed?'x':' '}] ${a.title} — ${a.minutes} min; due ${a.due_on}\n  ${a.description}\n  Faculty note: ${a.faculty_note||'None'}`).join('\n\n')}\n\n## Resource\n${d.resource.resource_name}: ${d.resource.resource}\n\n## Progress\n${p.progress.map(r=>`${r.recorded_on}: assessment ${r.score}%, attendance ${r.attendance}%, assignments ${r.completion}%\n${r.notes}`).join('\n\n')||'No follow-up records.'}\n\nFaculty-reviewed support only. No automated grading.\n\nDeveloped by Batch - 8 of CSE-A\n`;download(content,`nexora-plan-${p.id}.md`,'text/markdown');toast('Plan report exported.');}return <div><p className="form-description">Export only to an approved location. Reports contain student evidence.</p><div className="export-options"><button onClick={md}><Icon name="file" size={26}/><span><strong>Readable report</strong><small>Markdown · activities, evidence and progress</small></span><Icon name="download"/></button><button onClick={()=>{download(JSON.stringify({student:{name:s.name,roll:s.roll,semester:s.semester},plan:p},null,2),`nexora-plan-${p.id}.json`);toast('Structured plan exported.');}}><Icon name="code" size={26}/><span><strong>Structured data</strong><small>JSON · complete plan and execution trace</small></span><Icon name="download"/></button><button onClick={()=>{onClose();setTimeout(()=>window.print(),150);}}><Icon name="file" size={26}/><span><strong>Print / Save as PDF</strong><small>Use your browser’s print dialog</small></span><Icon name="external"/></button></div></div>;}

function Search({onClose}){const {workspace}=useApp();const [q,setQ]=useState('');const needle=q.trim().toLowerCase();const students=workspace.students.filter(s=>`${s.name} ${s.roll}`.toLowerCase().includes(needle)).slice(0,5);const plans=workspace.plans.filter(p=>`${p.data.title} ${workspace.students.find(s=>s.id===p.student_id)?.name}`.toLowerCase().includes(needle)).slice(0,4);return <><div className="search-input search-modal-input"><Icon name="search"/><input autoFocus placeholder="Search students, roll numbers or plans..." aria-label="Search workspace" value={q} onChange={e=>setQ(e.target.value)}/><kbd>ESC</kbd></div><div className="search-results">{students.length>0&&<div className="eyebrow">STUDENTS</div>}{students.map(s=><Link to={`/app/students/${s.id}`} key={s.id} onClick={onClose} className="search-result"><Avatar name={s.name} color={s.id}/><div><strong>{s.name}</strong><span>{s.roll} · Semester {s.semester}</span></div><Icon name="arrow" size={18}/></Link>)}{plans.length>0&&<div className="eyebrow">STUDY PLANS</div>}{plans.map(p=><Link to={`/app/plans/${p.id}`} key={p.id} onClick={onClose} className="search-result"><span className="search-plan-icon"><Icon name="layers"/></span><div><strong>{p.data.title}</strong><span>{p.status} · Revision {p.revision}</span></div><Icon name="arrow" size={18}/></Link>)}{!students.length&&!plans.length&&<Empty icon="search" title="No matches yet" description="Try a name, roll number or CSE topic."/>}</div></>;}

function Inbox({onClose}){const {workspace}=useApp();const drafts=workspace.plans.filter(p=>p.status==='Draft');const upcoming=workspace.plans.filter(p=>p.status==='Active').sort((a,b)=>a.data.review_on.localeCompare(b.data.review_on));return <><p className="form-description">A live review queue, derived from your study plan plans. No emails or push notifications are sent.</p><div className="inbox-list">{[...drafts,...upcoming].map(p=><Link className="inbox-item" to={`/app/plans/${p.id}`} onClick={onClose} key={p.id}><span className={`inbox-icon ${p.status==='Draft'?'orange':''}`}><Icon name={p.status==='Draft'?'layers':'calendar'}/></span><div><strong>{p.status==='Draft'?'Draft needs your review':`Review scheduled · ${formatDate(p.data.review_on)}`}</strong><p>{workspace.students.find(s=>s.id===p.student_id)?.name} · {p.course}</p></div><Icon name="chevron" size={18}/></Link>)}</div>{!drafts.length&&!upcoming.length&&<Empty icon="bell" title="You’re all caught up" description="Drafts and scheduled reviews will appear here."/>}</>;}

export function WorkspaceModal(){const {modal,setModal}=useApp();if(!modal)return null;const close=()=>setModal(null),props={...modal.payload,onClose:close};const titles={student:'Add a student',editStudent:'Edit student details',evidence:'Add performance evidence',generate:props.parentId?'Draft an adaptive revision':'Create an study plan',progress:'Log a progress check-in',import:'Bring your evidence together',editPlan:'Make the draft your own',approve:'Faculty approval',complete:'Complete study plan',archive:'Archive study plan',taskNote:'Implementation note',deleteStudent:'Delete student record',export:'Export study plan',search:'Find your next step',inbox:'Your review inbox',resetPassword:'Reset student password',studentTarget:'My target CGPA'};const wide=['editPlan','import'].includes(modal.type);return <Modal title={titles[modal.type]||'Nexora'} onClose={close} wide={wide}>{({student:<StudentForm {...props}/>,editStudent:<StudentForm {...props}/>,evidence:<EvidenceForm {...props}/>,progress:<EvidenceForm {...props}/>,generate:<GenerateForm {...props}/>,import:<ImportForm {...props}/>,editPlan:<EditPlanForm {...props}/>,approve:<ConfirmPlan type="approve" {...props}/>,complete:<ConfirmPlan type="complete" {...props}/>,archive:<ConfirmPlan type="archive" {...props}/>,taskNote:<TaskNote {...props}/>,deleteStudent:<DeleteStudent {...props}/>,export:<ExportPlan {...props}/>,search:<Search {...props}/>,inbox:<Inbox {...props}/>,resetPassword:<ResetPassword {...props}/>,studentTarget:<StudentTarget {...props}/>})[modal.type]}</Modal>;}
