import React, {useState} from 'react';
import {useApp,api,Link,Icon,Button,Badge,Avatar,Empty,Notice,TrendChart,formatDate,percent,recommendation,planDelta} from './core';

export function PlanDetail({id}){
 const {workspace,openModal,refresh,toast}=useApp();const [working,setWorking]=useState(false),[tab,setTab]=useState('Implementation');
 const p=workspace.plans.find(p=>p.id===Number(id));
 if(!p)return <Empty icon="layers" title="Plan not found" description="This plan may have been removed or belongs to another workspace."><Link to="/app/plans" className="btn btn-primary">All study plans</Link></Empty>;
 const s=workspace.students.find(s=>s.id===p.student_id),d=p.data,rec=recommendation(p);const done=d.activities.filter(a=>a.completed).length;
 const versions=workspace.plans.filter(x=>x.student_id===p.student_id&&x.course===p.course).sort((a,b)=>b.id-a.id);
 const points=[{label:'Baseline',score:d.baseline.score,attendance:d.baseline.attendance},...p.progress.map(r=>({label:formatDate(r.recorded_on),score:r.score,attendance:r.attendance}))];
 async function action(payload){setWorking(true);try{await api(`/plans/${p.id}`,payload,'PATCH');await refresh();toast('Implementation updated.');}catch(e){toast(e.message,'error');}finally{setWorking(false);}}
 return <div className="plan-detail"><div className="print-brand"><span className="mono">NEXORA / ACADEMIC STUDY PLAN STUDIO</span></div><Link className="back-link" to="/app/plans"><Icon name="back" size={16}/> All study plans</Link><div className="plan-detail-heading"><div><div className="plan-detail-eyebrow"><span className="eyebrow">STUDY PLAN {String(p.id).padStart(3,'0')} <span> / </span> REVISION {p.revision}</span><Badge>{p.status}</Badge></div><h1>{d.title}</h1><Link to={`/app/students/${s.id}`} className="plan-detail-student"><Avatar name={s.name} color={s.id} size="sm"/><strong>{s.name}</strong><span>{s.roll} · CSE-{s.section} · Semester {s.semester}</span><Icon name="arrowUp" size={15}/></Link></div><div className="button-row"><Button variant="secondary" icon="download" onClick={()=>openModal('export',{plan:p,student:s})}>Export plan</Button>{p.status==='Draft'&&<><Button variant="secondary" icon="edit" onClick={()=>openModal('editPlan',{plan:p})}>Edit draft</Button><Button icon="check" onClick={()=>openModal('approve',{plan:p})}>Approve plan</Button></>}{p.status==='Active'&&<Button icon="plus" onClick={()=>openModal('progress',{plan:p})}>Log progress</Button>}</div></div>
 {p.status==='Draft'&&<Notice icon="shield"><strong>Your perspective is the final step.</strong> This draft has not been implemented. Review the evidence, goals and activities before approval. {p.parent_id?'Approving this revision archives the previous active plan.':'Any existing active plan for this student and course will be archived.'}</Notice>}
 <div className="plan-layout"><div className="plan-main"><section className="card objective-card"><div className="card-heading"><h2>The objective</h2><Badge>{d.source}</Badge></div><p className="plan-objective">{d.objective}</p><div className="plan-targets"><div><span>Baseline assessment</span><strong>{d.baseline.score}%</strong></div><Icon name="arrow" size={25}/><div><span>Target assessment</span><strong className="blue-text">{d.target_score}%</strong></div><div><span>Duration</span><strong>{d.weeks} weeks</strong></div><div><span>Next review</span><strong>{formatDate(d.review_on)}</strong></div></div><div className="evidence-callout"><span className="eyebrow">GROUNDED IN YOUR EVIDENCE</span><p>{d.rationale}</p><span className="mono">{d.evidence_ids.map(x=>`E-${x}`).join(' · ')} / {formatDate(d.baseline.recorded_on,{day:'numeric',month:'long',year:'numeric'})}</span></div></section>
 <div className="tabs">{['Implementation','Progress & adaptation','Agent activity'].map(t=><button key={t} className={tab===t?'active':''} onClick={()=>setTab(t)}>{t}{t==='Implementation'&&<span>{done}/{d.activities.length}</span>}</button>)}</div>
 <section className={`card implementation-card ${tab==='Implementation'?'':'print-only'}`}><div className="card-heading"><div><h2>A manageable way forward</h2><p>{done} of {d.activities.length} activities completed · Faculty-managed checklist</p></div><span className="mono muted">{Math.round(done/d.activities.length*100)}%</span></div><div className="implementation-track"><i style={{width:`${done/d.activities.length*100}%`}}/></div><div className="task-list">{d.activities.map((a,i)=><article className={`task-item ${a.completed?'is-complete':''}`} key={i}><label className="task-checkbox"><input aria-label={`Complete activity: ${a.title}`} type="checkbox" checked={a.completed} disabled={p.status!=='Active'||working} onChange={e=>action({action:'task',index:i,completed:e.target.checked})}/><span><Icon name="check" size={15}/></span></label><div className="task-content"><div className="task-title"><h3>{a.title}</h3><span className="task-week">WEEK {a.week}</span></div><p>{a.description}</p><div className="task-meta"><span><Icon name="calendar" size={14}/>{formatDate(a.due_on)}</span><span><Icon name="clock" size={14}/>{a.minutes} min</span><span className="subtle-chip">{a.kind}</span><button className="text-link" disabled={p.status!=='Active'} onClick={()=>openModal('taskNote',{plan:p,index:i})}><Icon name="edit" size={14}/>{a.faculty_note?'Edit note':'Add note'}</button></div>{a.faculty_note&&<div className="task-note"><Icon name="file" size={15}/>{a.faculty_note}</div>}</div></article>)}</div>{p.status==='Active'&&<div className="implementation-footer"><span>{done===d.activities.length?'All activities complete. Review the outcome before closing.':'Check off activities as they are implemented.'}</span><Button variant="secondary" disabled={done!==d.activities.length} onClick={()=>openModal('complete',{plan:p})} icon="check">Complete plan</Button></div>}</section>
 <section className={`progress-detail-section ${tab==='Progress & adaptation'?'':'print-only'}`}><div className="card"><div className="card-heading"><div><h2>What has changed?</h2><p>Comparable assessment and attendance evidence</p></div>{p.status==='Active'&&<Button variant="secondary" icon="plus" onClick={()=>openModal('progress',{plan:p})}>Log check-in</Button>}</div><TrendChart points={points}/></div><div className={`card adaptation-card recommendation-${rec.tone}`}><div className="adaptation-icon"><Icon name="refresh" size={23}/></div><div><span className="eyebrow">PROGRESS EVALUATOR</span><h2>{rec.title}</h2><p>{rec.text}</p>{p.progress.length>0&&<span className="block muted">{planDelta(p)>0?'+':''}{planDelta(p)} percentage points from baseline. This does not establish causation.</span>}</div>{p.status==='Active'&&<Button variant="secondary" disabled={!p.progress.length||workspace.plans.some(x=>x.parent_id===p.id&&x.status==='Draft')} onClick={()=>openModal('generate',{studentId:s.id,course:p.course,parentId:p.id})} icon="layers">Draft a revision</Button>}</div><div className="card"><div className="card-heading"><h2>Check-in history</h2></div>{p.progress.length?<div className="table-scroll"><table><thead><tr><th>Date</th><th>Assessment</th><th>Attendance</th><th>Completion</th><th>Faculty reflection</th></tr></thead><tbody>{[...p.progress].reverse().map(r=><tr key={r.id}><td className="nowrap">{formatDate(r.recorded_on)}</td><td>{r.score}%</td><td>{r.attendance}%</td><td>{r.completion}%</td><td className="note-cell">{r.notes||'—'}</td></tr>)}</tbody></table></div>:<Empty icon="chart" title="The next chapter is yours" description="After implementing support, log a follow-up assessment to evaluate progress."/>}</div></section>
 <section className={`card agent-trace-card ${tab==='Agent activity'?'':'print-only'}`}><div className="card-heading"><div><h2>Behind this study plan</h2><p>Execution trace and decision checkpoints, not hidden model reasoning</p></div></div><ol className="agent-trace">{d.trace.map((t,i)=><li key={t.agent}><span className={`trace-step ${t.status==='awaiting'?'awaiting':''}`}><Icon name={t.status==='awaiting'?'clock':'check'} size={17}/></span><div><div className="trace-heading"><h3>{t.agent}</h3><span>0{i+1} / {t.status==='awaiting'?'AWAITING REVIEW':'COMPLETE'}</span></div><p>{t.detail}</p></div></li>)}</ol><div className="trace-meta"><span>Source <strong>{d.source}</strong></span><span>Model / version <strong>{d.model}</strong></span><span>Created <strong>{formatDate(p.created_at)}</strong></span></div></section>
 </div><aside className="plan-sidebar"><section className="card plan-context"><div className="card-heading"><h2>Plan at a glance</h2><Icon name="info" size={19}/></div><dl><div><dt>Student</dt><dd>{s.name}</dd></div><div><dt>Subject</dt><dd>{workspace.courses[p.course].name}</dd></div><div><dt>Support at baseline</dt><dd><Badge>{d.risk.level}</Badge></dd></div><div><dt>Faculty owner</dt><dd>{d.approved_by||'Awaiting approval'}</dd></div><div><dt>Planned effort</dt><dd>{d.activities.reduce((n,a)=>n+a.minutes,0)} minutes</dd></div></dl></section><section className="card recommended-resource"><span className={`course-symbol course-${workspace.courses[p.course].color}`}><Icon name="book" size={24}/></span><span className="eyebrow">CURATED LEARNING RESOURCE</span><h2>{d.resource.resource_name}</h2><p>Selected for {p.course}. Review for syllabus alignment before assigning.</p><a href={d.resource.resource} target="_blank" rel="noreferrer" className="btn btn-secondary">Open resource<Icon name="external" size={17}/></a></section><section className="card version-card"><div className="card-heading"><h2>Related plans</h2><Icon name="layers" size={18}/></div>{versions.map(v=><Link className={`version-item ${v.id===p.id?'current':''}`} key={v.id} to={`/app/plans/${v.id}`}><div><strong>Revision {v.revision}</strong><span>{formatDate(v.created_at)} · #{v.id}</span></div><Badge>{v.status}</Badge></Link>)}</section>{p.status!=='Archived'&&<button className="text-link archive-link" onClick={()=>openModal('archive',{plan:p})}><Icon name="layers" size={16}/>Archive this plan</button>}<p className="sidebar-footnote"><Icon name="shield" size={16}/>A support plan, not an automated decision. Faculty remain responsible for academic judgment.</p></aside></div></div>;
}
